# Generated by Django 4.1.4 on 2022-12-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
    ]
