# Generated by Django 4.1.4 on 2022-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="time_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
